# Generated by Django 5.0.2 on 2024-03-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_register_email_remove_register_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='image',
        ),
    ]
