# Generated by Django 5.0.2 on 2024-03-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_register_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
